package skripsi.nabila_medicat.model;

import android.view.Display;

import java.time.MonthDay;
import java.util.ArrayList;

public class MasterData {
    public static ArrayList<ModelPenyakit> P001 = new ArrayList<>();
    public static ArrayList<ModelPenyakit> P002 = new ArrayList<>();
    public static ArrayList<ModelPenyakit> P003 = new ArrayList<>();
    public static ArrayList<ModelPenyakit> P004 = new ArrayList<>();
    public static ArrayList<ModelPenyakit> P005 = new ArrayList<>();
    public static ArrayList<ModelPenyakit> P006 = new ArrayList<>();
    public static ArrayList<ModelPenyakit> P007 = new ArrayList<>();


    public static ArrayList<ModelPenyakit> Answer = new ArrayList<>();

    public static ArrayList<String> pertanyaan = new ArrayList<>();


    public void GenerateNilai(){
        P001.clear();
        P002.clear();
        P003.clear();
        P004.clear();
        P005.clear();
        P006.clear();
        P007.clear();

        ModelPenyakit mP1 = new ModelPenyakit();
        mP1.setKodeGejala("G029");
        mP1.setNamaPenyakit("FLUTD");
        mP1.setNamaGejala("sulit buang air kecil");
        mP1.setKodePenyakit("P001");
        mP1.setCF(0.8);
        ModelPenyakit mP2 = new ModelPenyakit();
        mP2.setKodeGejala("G003");
        mP2.setNamaPenyakit("FLUTD");
        mP2.setNamaGejala("buang air kecil berdarah");
        mP2.setKodePenyakit("P001");
        mP2.setCF(0.8);
        ModelPenyakit mP3 = new ModelPenyakit();
        mP3.setKodeGejala("G027");
        mP3.setNamaPenyakit("FLUTD");
        mP3.setNamaGejala("sering menjilat alat kelamin");
        mP3.setKodePenyakit("P001");
        mP3.setCF(0.6);
        ModelPenyakit mP4 = new ModelPenyakit();
        mP4.setKodeGejala("G004");
        mP4.setNamaPenyakit("FLUTD");
        mP4.setNamaGejala("buang air kecil tidak pada tempatnya");
        mP4.setKodePenyakit("P001");
        mP4.setCF(0.4);
        ModelPenyakit mP5 = new ModelPenyakit();
        mP5.setKodeGejala("G010");
        mP5.setNamaPenyakit("FLUTD");
        mP5.setNamaGejala("frekuensi buang air kecil meningkat");
        mP5.setKodePenyakit("P001");
        mP5.setCF(0.8);
        P001.add(mP1);
        P001.add(mP2);
        P001.add(mP3);
        P001.add(mP4);
        P001.add(mP5);

        ModelPenyakit mP6 = new ModelPenyakit();
        mP6.setKodeGejala("G021");
        mP6.setNamaPenyakit("Chlamydia");
        mP6.setNamaGejala("mata berair dan belekan");
        mP6.setKodePenyakit("P002");
        mP6.setCF(0.6);
        ModelPenyakit mP7 = new ModelPenyakit();
        mP7.setKodeGejala("G023");
        mP7.setNamaPenyakit("Chlamydia");
        mP7.setNamaGejala("mata merah dan bengkak");
        mP7.setKodePenyakit("P002");
        mP7.setCF(0.6);
        ModelPenyakit mP8 = new ModelPenyakit();
        mP8.setKodeGejala("G009");
        mP8.setNamaPenyakit("Chlamydia");
        mP8.setNamaGejala("flu");
        mP8.setKodePenyakit("P002");
        mP8.setCF(0.6);
        ModelPenyakit mP9 = new ModelPenyakit();
        mP9.setKodeGejala("G028");
        mP9.setNamaPenyakit("Chlamydia");
        mP9.setNamaGejala("sulit bernapas");
        mP9.setKodePenyakit("P002");
        mP9.setCF(0.6);
        ModelPenyakit mP10 = new ModelPenyakit();
        mP10.setKodeGejala("G022");
        mP10.setNamaPenyakit("Chlamydia");
        mP10.setNamaGejala("mata bernanah");
        mP10.setKodePenyakit("P002");
        mP10.setCF(0.8);
        P002.add(mP6);
        P002.add(mP7);
        P002.add(mP8);
        P002.add(mP9);
        P002.add(mP10);

        ModelPenyakit mP11 = new ModelPenyakit();
        mP11.setKodeGejala("G025");
        mP11.setNamaPenyakit("Helminthiasis");
        mP11.setNamaGejala("perut membesar");
        mP11.setKodePenyakit("P003");
        mP11.setCF(0.8);
        ModelPenyakit mP12 = new ModelPenyakit();
        mP12.setKodeGejala("G024");
        mP12.setNamaPenyakit("Helminthiasis");
        mP12.setNamaGejala("muntah disertai cacing");
        mP12.setKodePenyakit("P003");
        mP12.setCF(0.8);
        ModelPenyakit mP13 = new ModelPenyakit();
        mP13.setKodeGejala("G008");
        mP13.setNamaPenyakit("Helminthiasis");
        mP13.setNamaGejala("diare disertai cacing");
        mP13.setKodePenyakit("P003");
        mP13.setCF(0.8);
        ModelPenyakit mP14 = new ModelPenyakit();
        mP14.setKodeGejala("G001");
        mP14.setNamaPenyakit("Helminthiasis");
        mP14.setNamaGejala("bulu rontok dan kusam");
        mP14.setKodePenyakit("P003");
        mP14.setCF(0.6);
        ModelPenyakit mP15 = new ModelPenyakit();
        mP15.setKodeGejala("G002");
        mP15.setNamaPenyakit("Helminthiasis");
        mP15.setNamaGejala("batuk");
        mP15.setKodePenyakit("P003");
        mP15.setCF(0.4);
        P003.add(mP11);
        P003.add(mP12);
        P003.add(mP13);
        P003.add(mP14);
        P003.add(mP15);

        ModelPenyakit mP16 = new ModelPenyakit();
        mP16.setKodeGejala("G011");
        mP16.setNamaPenyakit("Ringworm");
        mP16.setNamaGejala("gatal dan ruam");
        mP16.setKodePenyakit("P004");
        mP16.setCF(0.6);
        ModelPenyakit mP17 = new ModelPenyakit();
        mP17.setKodeGejala("G015");
        mP17.setNamaPenyakit("Ringworm");
        mP17.setNamaGejala("kulit bersisik");
        mP17.setKodePenyakit("P004");
        mP17.setCF(0.8);
        ModelPenyakit mP18 = new ModelPenyakit();
        mP18.setKodeGejala("G016");
        mP18.setNamaPenyakit("Ringworm");
        mP18.setNamaGejala("kulit mati menyerupai ketombe");
        mP18.setKodePenyakit("P004");
        mP18.setCF(0.8);
        ModelPenyakit mP19 = new ModelPenyakit();
        mP19.setKodeGejala("G018");
        mP19.setNamaPenyakit("Ringworm");
        mP19.setNamaGejala("luka didaerah tertentu");
        mP19.setKodePenyakit("P004");
        mP19.setCF(0.8);
        ModelPenyakit mP20 = new ModelPenyakit();
        mP20.setKodeGejala("G019");
        mP20.setNamaPenyakit("Ringworm");
        mP20.setNamaGejala("luka membentuk lingkaran");
        mP20.setKodePenyakit("P004");
        mP20.setCF(0.6);
        P004.add(mP16);
        P004.add(mP17);
        P004.add(mP18);
        P004.add(mP19);
        P004.add(mP20);

        ModelPenyakit mP21 = new ModelPenyakit();
        mP21.setKodeGejala("G012");
        mP21.setNamaPenyakit("FIV");
        mP21.setNamaGejala("kehilangan berat badan");
        mP21.setKodePenyakit("P005");
        mP21.setCF(0.8);
        ModelPenyakit mP22 = new ModelPenyakit();
        mP22.setKodeGejala("G006");
        mP22.setNamaPenyakit("FIV");
        mP22.setNamaGejala("demam");
        mP22.setKodePenyakit("P005");
        mP22.setCF(0.6);
        ModelPenyakit mP23 = new ModelPenyakit();
        mP23.setKodeGejala("G007");
        mP23.setNamaPenyakit("FIV");
        mP23.setNamaGejala("diare");
        mP23.setKodePenyakit("P005");
        mP23.setCF(0.6);
        ModelPenyakit mP24 = new ModelPenyakit();
        mP24.setKodeGejala("G030");
        mP24.setNamaPenyakit("FIV");
        mP24.setNamaGejala("tidak nafsu makan");
        mP24.setKodePenyakit("P005");
        mP24.setCF(0.6);
        ModelPenyakit mP25 = new ModelPenyakit();
        mP25.setKodeGejala("G017");
        mP25.setNamaPenyakit("FIV");
        mP25.setNamaGejala("lesu");
        mP25.setKodePenyakit("P005");
        mP25.setCF(0.8);
        P005.add(mP21);
        P005.add(mP22);
        P005.add(mP23);
        P005.add(mP24);
        P005.add(mP25);

        ModelPenyakit mP26 = new ModelPenyakit();
        mP26.setKodeGejala("G026");
        mP26.setNamaPenyakit("Scabies");
        mP26.setNamaGejala("gatal dan ruam");
        mP26.setKodePenyakit("P006");
        mP26.setCF(0.6);
        ModelPenyakit mP27 = new ModelPenyakit();
        mP27.setKodeGejala("G005");
        mP27.setNamaPenyakit("Scabies");
        mP27.setNamaGejala("kulit bersisik");
        mP27.setKodePenyakit("P006");
        mP27.setCF(0.6);
        ModelPenyakit mP28 = new ModelPenyakit();
        mP28.setKodeGejala("G014");
        mP28.setNamaPenyakit("Scabies");
        mP28.setNamaGejala("kulit mati menyerupai ketombe");
        mP28.setKodePenyakit("P006");
        mP28.setCF(0.6);
        ModelPenyakit mP29 = new ModelPenyakit();
        mP29.setKodeGejala("G011");
        mP29.setNamaPenyakit("Scabies");
        mP29.setNamaGejala("luka didaerah tertentu");
        mP29.setKodePenyakit("P006");
        mP29.setCF(0.8);
        ModelPenyakit mP30 = new ModelPenyakit();
        mP30.setKodeGejala("G019");
        mP30.setNamaPenyakit("Scabies");
        mP30.setNamaGejala("luka membentuk lingkaran");
        mP30.setKodePenyakit("P006");
        mP30.setCF(0.6);
        P006.add(mP26);
        P006.add(mP27);
        P006.add(mP28);
        P006.add(mP29);
        P006.add(mP30);

        ModelPenyakit mP31 = new ModelPenyakit();
        mP31.setKodeGejala("G028");
        mP31.setNamaPenyakit("Rhinotracheitis");
        mP31.setNamaGejala("sulit bernapas");
        mP31.setKodePenyakit("P007");
        mP31.setCF(0.8);
        ModelPenyakit mP32 = new ModelPenyakit();
        mP32.setKodeGejala("G009");
        mP32.setNamaPenyakit("Rhinotracheitis");
        mP32.setNamaGejala("flu");
        mP32.setKodePenyakit("P007");
        mP32.setCF(0.6);
        ModelPenyakit mP33 = new ModelPenyakit();
        mP33.setKodeGejala("G013");
        mP33.setNamaPenyakit("Rhinotracheitis");
        mP33.setNamaGejala("keluar lendir dari hidung");
        mP33.setKodePenyakit("P007");
        mP33.setCF(0.8);
        ModelPenyakit mP34 = new ModelPenyakit();
        mP34.setKodeGejala("G006");
        mP34.setNamaPenyakit("Rhinotracheitis");
        mP34.setNamaGejala("demam");
        mP34.setKodePenyakit("P007");
        mP34.setCF(0.6);
        ModelPenyakit mP35 = new ModelPenyakit();
        mP35.setKodeGejala("G020");
        mP35.setNamaPenyakit("Rhinotracheitis");
        mP35.setNamaGejala("mata bengkak");
        mP35.setKodePenyakit("P007");
        mP35.setCF(0.6);
        P007.add(mP31);
        P007.add(mP32);
        P007.add(mP33);
        P007.add(mP34);
        P007.add(mP35);
    }

    public void generatePertanyaan() {
        pertanyaan.clear();
        pertanyaan.add("Kucing mengalami bulu rontok dan kusam");
        pertanyaan.add("Kucing mengalami batuk");
        pertanyaan.add("Kucing mengalami buang air kecil berdarah");
        pertanyaan.add("Kucing mengalami buang air kecil tidak pada tempatnya");
        pertanyaan.add("Kucing mengalami bulu membotak");
        pertanyaan.add("Kucing mengalami demam");
        pertanyaan.add("Kucing mengalami diare");
        pertanyaan.add("Kucing mengalami diare disertai cacing");
        pertanyaan.add("Kucing mengalami flu");
        pertanyaan.add("Kucing mengalami frekuensi buang air kecil meningkat");
        pertanyaan.add("Kucing mengalami gatal dan ruam");
        pertanyaan.add("Kucing mengalami kehilangan berat badan");
        pertanyaan.add("Kucing mengalami keluar lendir dari hidung");
        pertanyaan.add("Kucing mengalami koreng dan penebalan kulit ditelinga");
        pertanyaan.add("Kucing mengalami kulit bersisik");
        pertanyaan.add("Kucing mengalami kulit mati menyerupai ketombe");
        pertanyaan.add("Kucing mengalami lesu");
        pertanyaan.add("Kucing mengalami luka didaerah tertentu");
        pertanyaan.add("Kucing mengalami luka membentuk lingkaran");
        pertanyaan.add("Kucing mengalami mata bengkak");
        pertanyaan.add("Kucing mengalami mata berair dan belekan");
        pertanyaan.add("Kucing mengalami mata bernanah");
        pertanyaan.add("Kucing mengalami mata merah dan bengkak");
        pertanyaan.add("Kucing mengalami muntah disertai cacing");
        pertanyaan.add("Kucing mengalami perut membesar");
        pertanyaan.add("Kucing mengalami sering menggaruk kepala");
        pertanyaan.add("Kucing mengalami sering menjilat alat kelamin");
        pertanyaan.add("Kucing mengalami sulit bernapas");
        pertanyaan.add("Kucing mengalami sulit buang air kecil");
        pertanyaan.add("Kucing mengalami tidak nafsu makan");
    }
}
